### PR TITLE
added docker file and compose

### PR DESCRIPTION
**Pull request by palashkulsh**
added dockerfile and docker compose file for instant set up of server

### CODE REVIEW

**Comment by SumeetMoray** [comment]
thank you for your contribution !

**Comment by palashkulsh** [comment]
@SumeetMoray its a really nice project. are you still maintaining it actively.

**Comment by SumeetMoray** [comment]
Thank you ... good to know you like the project !
Yes this project is being maintained actively !

We are also in the process of looking for ways to fund the project so that we can hire full time developers to contribute to the project !

**Comment by palashkulsh** [comment]
i really feel good about this project, though i dont know much about android development, i can contribute on other technical stuff.

**Comment by SumeetMoray** [comment]
yes  ... you dont need android skills ... there is requirement in backend and database side also ...

We are open to any kind of contribution people are interested in making ! 
People can contribute in Non-technical way also !

**Comment by palashkulsh** [comment]
that is cool, I primarily work on backend and database. I will learn android on the way. Do you have any open issue/feature list that we are planning to add? So that we can start working as and when time allows.

**Comment by SumeetMoray** [comment]
Yes offcourse ... we do have that list ... but there is nothing to hurry ...  if you decide to work on any feature ... let us know and have a chat in advance !

1. Improved Search - We need a better full text search in the app -  preferably using Postgres full text search feature ... 
2. Payment Gateway Integration is required ... (Although its not mandatory but good to have)
3. We want to explore if we can migrate to Hasura GraphQL technology

**Comment by palashkulsh** [comment]
sure, lets catch up sometime. I'll take a look at the code in the meantime.

**Pull request merged**
